version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD=EE-85*q@
    command: 
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306